### ISSUE TITLE
Wouxun KG-D901

### ISSUE THREAD

**Issue by HAMradioCanada** [m0ivq/kg-uv920p-display#1]
I have a Wouxun KG-D901 that is not starting up. Problem seems to be on boot. It locks up 00000.000000 and the date and time below.    

Using DFU method md380 holding keys can select past programmed frequencies. Once release PTT upper key locks up to 00000.00000.

Thoughts around reloading firmware .bin,  if I had factory .bin

**Comment by m0ivq** [comment]
No idea I'm afraid, I'm not familiar with the KG-D901. None of the analogue Wouxun radios have the option to upgrade firmware so it's not something I've looked at. Your only options are to go back to your dealer or contact Wouxun. Sometimes they can be really helpful and sometimes you don't get any response whatsoever!
